server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter

application:
  config:
    auth-url: http://localhost:9010/api/v1/auth